insert into cards (name, position, rating) values
  ('Kylian Mbappé', 'ATT', 91),
  ('Erling Haaland', 'ATT', 91),
  ('Jude Bellingham', 'MID', 90),
  ('Vinícius Júnior', 'ATT', 89),
  ('Rodri', 'MID', 89),
  ('Mohamed Salah', 'ATT', 89),
  ('Lamine Yamal', 'ATT', 89),
  ('Virgil van Dijk', 'DEF', 89),
  ('Thibaut Courtois', 'GK', 89),
  ('Lionel Messi', 'ATT', 88),
  ('Harry Kane', 'ATT', 88),
  ('Florian Wirtz', 'MID', 88),
  ('Jamal Musiala', 'MID', 88),
  ('Alisson Becker', 'GK', 88),
  ('Kevin De Bruyne', 'MID', 87),
  ('Bukayo Saka', 'ATT', 87),
  ('Pedri', 'MID', 87),
  ('Federico Valverde', 'MID', 87),
  ('Lautaro Martínez', 'ATT', 87),
  ('Gianluigi Donnarumma', 'GK', 87),
  ('Phil Foden', 'MID', 86),
  ('Robert Lewandowski', 'ATT', 86),
  ('Antonio Rüdiger', 'DEF', 86),
  ('Martin Ødegaard', 'MID', 86),
  ('Khvicha Kvaratskhelia', 'ATT', 86),
  ('Julián Álvarez', 'ATT', 86),
  ('Cole Palmer', 'MID', 86),
  ('Declan Rice', 'MID', 86),
  ('William Saliba', 'DEF', 86),
  ('Emiliano Martínez', 'GK', 86),
  ('Antoine Griezmann', 'ATT', 85),
  ('Achraf Hakimi', 'DEF', 85),
  ('Théo Hernandez', 'DEF', 85),
  ('Victor Osimhen', 'ATT', 85),
  ('Michael Olise', 'MID', 85),
  ('Gavi', 'MID', 84),
  ('Eduardo Camavinga', 'MID', 84),
  ('Aurélien Tchouaméni', 'MID', 84),
  ('Bradley Barcola', 'ATT', 84),
  ('Désiré Doué', 'MID', 83);
